export var locations=[
    ["Pikes Peak",[38.840243, -105.042914]],
    ["Garden of the Gods",[38.877726, -104.871075]],
    ["Black Canyon of the Gunnison National Park",[38.575334, -107.741822]],
    ["Mesa Verde National Park",[37.229993, -108.463400]],
    ["Shiprock",[36.788778, -108.687580]],
    ["Horseshoe Bend",[]],
    ["Grand Canyon",[]],
    ["Belly of the Dragon",[]],
    ["Bryce Canyon National Park",[]],
    ["Zion National Park",[]],
    ["Death Valley",[]],
    ["Big Pine Lakes",[]],
    ["Yosemite",[]],
    ["Rainbow Pools",[]],
    ["Sequoia National Forest",[]],
    ["PCH",[]],
    ["Big Sur",[]],
    ["Point Lobos",[]],
    ["Taco Bell",[]],
    ["Golden Gate Bridge",[]],
    ["Lake Tahoe",[]],
    ["Eagle Falls/ Lake",[]],
    ["Burney Falls",[]],
    ["Crater Lake",[]],
    ["Tamolitch Blue Pool",[]],
    ["Mt. Hood Skibowl",[]],
    ["Colombia River Gorge",[]],
    ["Mount Rainier",[]],
    ["Green River Gorge",[]],
    ["Sesqualmy Falls",[]],
    ["Glacier National Park",[]],
    ["Yellowstone",[]],
    ["Grand Teton",[]],
    ["Crazy Horse",[]],
    ["Mt. Rushmore",[]],
    ["Custer State Park",[]]];