export var locations=[
    ["Start and End",[42.612250, -83.079412],"The beginning of my first cross country trip. Starting and ending in Sterling Heights, MI"],
    ["Pikes Peak",[38.840243, -105.042914],"Welcome to the first place I ever struggled to breathe. Pikes Peak is tall as hell and my whole family got sick from the altitude change."],
    ["Garden of the Gods",[38.877726, -104.871075],"The grandest because we're already here stop ever. Awesome for rock climbing and pics."],
    ["Black Canyon of the Gunnison National Park",[38.575334, -107.741822],"The least safe National Park. 2000 foot sheer cliffs without a single railing or anyone to see you fall"],
    ["Mesa Verde National Park",[37.229993, -108.463400],"Check out the cliff dwellings. It's still wild to me that this was bui;t with primative tools."],
    ["Shiprock",[36.788778, -108.687580],"the biggest rock ever. One big rock in the middle of a flat desert that can be seen from miles away."],
    ["Horseshoe Bend",[36.879232, -111.510620],"If you want scenic, you've come to the right place. A beautiful winding river with cliffs higher than a skyscraper."],
    ["Grand Canyon National Park",[36.198336, -112.052502],"Lives up to the name. Definitely the biggest natural structure I've ever seen."],
    ["Belly of the Dragon",[37.211516, -112.685129],"If you want cool and off the beaten path, then you've found the right place. Leave your name and take some pictures."],
    ["Bryce Canyon National Park",[37.598327, -112.193431],"Hit up the Navajo Loop and hike the hoodoos, but beware your calves will be burning. The entire trail holds a harsh incline."],
    ["Zion National Park",[37.299564, -113.024673],"Possibly the best hiking park in the US. The Narrows and Angels Landing will never let you down."],
    ["Las Vegas",[36.177306, -115.157714],"A quick stop to see some non-nature beauty and admire the strip."],
    ["Death Valley National Park",[36.596858, -117.135856],"Gonna be honest not much to see here. Can't hike because it's 115+ degrees and there isn't much scenery. The salt flats here were kinda cool tho."],
    ["Big Pine Lakes",[37.128597, -118.434133],"Could have been the highlight of the trip with better planning, but the hike is so long we didn't finish. If you have the WHOLE day then do it!"],
    ["Yosemite National Park",[37.856230, -119.540167],"Yosemite is THE National Park. They use it's pictures to sell going to the parks for a reason. THe waterfalls are incredible and the mile high lakes are even better."],
    ["Rainbow Pools",[37.822627, -120.014278],"I imagine this would have been THE SPOT back in the day. It's basically a series of natural pools connected by small falls. Perfect for cliff jumping."],
    ["Sequoia National Forest",[36.481142, -118.567471],"You think you've seen big, but you haven't unless you've seen these trees. If all other trees are baby groot, then these are the real deal"],
    ["Pacific Coast Highway",[35.565981, -121.109703],"It's up for debate but the most beautiful view you can get from driving on a highway. Enjoy mountains, the ocean, maybe even a whale, and some hot cars."],
    ["Big Sur",[36.271046, -121.811090],"Check out the wreckage from earthquakes over the years along the coastline."],
    ["Point Lobos Nature Preserve",[36.515785, -121.937039],"If you want to see some fauna but don't want to go to the zoo. First place I saw a group of seals in the wild"],
    ["Taco Bell",[37.597651, -122.503431],"The grandest, most glorious stop on our trip. Taco Bell reigns supreme."],
    ["Golden Gate Bridge",[37.819937, -122.478534],"Probably the most famous bridge in America. Go pretend like you're in Full House or somethin'"],
    ["Pope Beach, Lake Tahoe",[38.937881, -120.032421],"Take it slow. Relax and breathe. Every long trip needs some down time to recharge."],
    ["Eagle Falls/ Lake",[38.951923, -120.113322],"Wow, just wow! Definitely my favorite trip ever. Climb past a waterfall, to swim through a lake, out to an island, while you're surrounded by mountains."],
    ["Burney Falls",[41.011992, -121.651823],"Ice Water Alert. The falls are magnificent, but it seems to be the Instagram selfie capital of the world."],
    ["Crater Lake National Park",[42.978863, -122.083308],"That's some dark water. If you're scared of the ocean, this is worse. There is no shallow, only deep. Excellent cliff jumping!"],
    ["Tamolitch Blue Pool",[44.312149, -122.027085],"That's some blue ass water. You ever wanted to go swimming in a pool of Gatorade? Well don't cuz you can't handle the cold."],
    ["Mt. Hood Skibowl",[45.301881, -121.772288],"A traditional touristy stop. A luge sled down a mountain with beautiful views. You can bike or ski or whatever else too."],
    ["Colombia River Gorge",[45.576839, -122.116303],"Man, I wanna live here. Tons of impressive waterfalls within a few miles. Everybody local treated it as a part of their everyday life, so it didn't feel touristy. Just unbelievably beautiful."],
    ["Mount Rainier National Parke",[46.879281, -121.726988],"Kinda funky how the flowers can be in full bloom and there can be feet of snow all around. Tremendous contrast and the flowers are PrEtTy"],
    ["Green River Gorge",[47.290568, -121.973473],"Out in the boonies! Good luck finding it. If you're close then you've probably been there and if you're not close then it's probalt not worth it."],
    ["Snoqualmie Falls",[47.542259, -121.838099],"Underappreciated!!! There's not much to do, but man ain't she pretty. Visit for the hydroelectric history."],
    ["Glacier National Park",[48.758474, -113.780080],"Give me an extra week here. Unfortunatley half of the park was inaccessible due to Covid, but every hike is sweet."],
    ["Yellowstone National Park",[44.413990, -110.588370],"You wanna go to another planet? Screw that. Just go to Yellowstone. The ground is oozing, colorful, and blowing smoke. For real though, it has a little bit of everything. Best Park no doubt."],
    ["Grand Teton National Park",[43.737828, -110.791692],"A little piece of the Swiss Alps in your own backyard. If you wanna fight a bear this is the place."],
    ["Crazy Horse",[43.836565, -103.623415],"They sure are taking their sweet time. They were working on it whenmy dad was a little kid, and there;s still no end in sight."],
    ["Mt. Rushmore National Memorial",[43.877734, -103.457221],"Go here before anything else on the trip. You'll enjoy it more that way. It's awesome, but doesn't measure up to places like Grand Canyon or Yellowstone."],
    ["Custer State Park",[43.760759, -103.371029],"A rancher's paradise. Go herd some buffalo. Just don't let them swarm your car."]];